[workspace]
members = ["send", "receive"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5.53", features = ["derive"] }
pcap = "2.4.0"
static_assertions = "1.1"