[package]
name = "net_stack"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
pcap = { workspace = true }
static_assertions ={ workspace = true }
protocol = { path = "../protocol" }